// EU/EEA/Switzerland nationalities are exempt from the French work-permit
// (titre de séjour) requirement — used to decide who counts as "foreign" for
// Registre du personnel highlighting and Dossier salarié's Titre/VISA slot.
export const EU_EEA_CH_NATIONALITY_MARKERS = [
  "FRANCE",
  "FRANÇAISE",
  "FRANCAISE",
  "FRANÇAIS",
  "FRANCAIS",
  "FR",
  "ALLEMAGNE",
  "ALLEMANDE",
  "DE",
  "AUTRICHE",
  "AUTRICHIENNE",
  "AT",
  "BELGIQUE",
  "BELGE",
  "BE",
  "BULGARIE",
  "BULGARE",
  "BG",
  "CHYPRE",
  "CHYPRIOTE",
  "CY",
  "CROATIE",
  "CROATE",
  "HR",
  "DANEMARK",
  "DANOISE",
  "DK",
  "ESPAGNE",
  "ESPAGNOLE",
  "ES",
  "ESTONIE",
  "ESTONIENNE",
  "EE",
  "FINLANDE",
  "FINLANDAISE",
  "FI",
  "GRÈCE",
  "GRECE",
  "GRECQUE",
  "GR",
  "HONGRIE",
  "HONGROISE",
  "HU",
  "IRLANDE",
  "IRLANDAISE",
  "IE",
  "ITALIE",
  "ITALIENNE",
  "IT",
  "LETTONIE",
  "LETTONE",
  "LV",
  "LITUANIE",
  "LITUANIENNE",
  "LT",
  "LUXEMBOURG",
  "LUXEMBOURGEOISE",
  "LU",
  "MALTE",
  "MALTAISE",
  "MT",
  "PAYS-BAS",
  "NÉERLANDAISE",
  "NEERLANDAISE",
  "NL",
  "POLOGNE",
  "POLONAISE",
  "PL",
  "PORTUGAL",
  "PORTUGAISE",
  "PT",
  "TCHÉQUIE",
  "TCHEQUIE",
  "RÉPUBLIQUE TCHÈQUE",
  "REPUBLIQUE TCHEQUE",
  "TCHÈQUE",
  "TCHEQUE",
  "CZ",
  "ROUMANIE",
  "ROUMAINE",
  "RO",
  "SLOVAQUIE",
  "SLOVAQUE",
  "SK",
  "SLOVÉNIE",
  "SLOVENIE",
  "SLOVÈNE",
  "SLOVENE",
  "SI",
  "SUÈDE",
  "SUEDE",
  "SUÉDOISE",
  "SUEDOISE",
  "SE",
  // EEA + Switzerland (same work-permit exemption in practice)
  "ISLANDE",
  "ISLANDAISE",
  "IS",
  "LIECHTENSTEIN",
  "LI",
  "NORVÈGE",
  "NORVEGE",
  "NORVÉGIENNE",
  "NORVEGIENNE",
  "NO",
  "SUISSE",
  "SUISSESSE",
  "CH",
];

export function isForeignNationality(nationalite: string | null | undefined): boolean {
  if (!nationalite) return false;
  return !EU_EEA_CH_NATIONALITY_MARKERS.includes(nationalite.trim().toUpperCase());
}
